<?php

use CodeIgniter\Router\RouteCollection;

/**
 * @var RouteCollection $routes
 */
$routes->get('/', 'AuthController::loginForm');
$routes->get('packages', 'PackageController::publicIndex');
$routes->get('packages/register/(:num)', 'PackageController::register/$1');

$routes->get('app/login', 'AuthController::loginForm');
$routes->post('app/login', 'AuthController::loginSubmit');
$routes->get('app/unauthorized', 'AuthController::unauthorized', ['filter' => 'webauth']);
$routes->get('app/forgot-password', 'AuthController::forgotPasswordForm');
$routes->post('app/forgot-password', 'AuthController::forgotPasswordSubmit');
$routes->get('app/reset-password', 'AuthController::resetPasswordForm');
$routes->post('app/reset-password', 'AuthController::resetPasswordSubmit');
$routes->post('app/logout', 'AuthController::logout', ['filter' => 'webauth']);
$routes->get('app', 'DashboardController::index', ['filter' => 'webauth:dashboard.view']);
$routes->get('app/seasons', 'SeasonController::index', ['filter' => 'webauth:rbac.manage']);
$routes->post('app/seasons', 'SeasonController::createSeason', ['filter' => 'webauth:rbac.manage']);
$routes->post('app/seasons/activate', 'SeasonController::activateSeason', ['filter' => 'webauth:rbac.manage']);
$routes->get('app/pilgrims', 'PilgrimController::index', ['filter' => 'webauth:pilgrims.view']);
$routes->post('app/pilgrims', 'PilgrimController::createPilgrim', ['filter' => 'webauth:pilgrims.manage']);
$routes->get('app/pilgrims/import', 'PilgrimController::importPage', ['filter' => 'webauth:pilgrims.manage']);
$routes->post('app/pilgrims/import', 'PilgrimController::importMofaCsv', ['filter' => 'webauth:pilgrims.manage']);
$routes->post('app/pilgrims/update', 'PilgrimController::updatePilgrim', ['filter' => 'webauth:pilgrims.manage']);
$routes->post('app/pilgrims/delete', 'PilgrimController::deletePilgrim', ['filter' => 'webauth:pilgrims.manage']);
$routes->get('app/pilgrims/add', 'PilgrimController::add', ['filter' => 'webauth:pilgrims.manage']);
$routes->get('app/pilgrims/(:num)/edit', 'PilgrimController::edit/$1', ['filter' => 'webauth:pilgrims.manage']);
$routes->get('app/bookings', 'BookingController::index', ['filter' => 'webauth:bookings.view']);
$routes->get('app/bookings/(:num)/voucher', 'BookingController::voucher/$1', ['filter' => 'webauth:bookings.view']);
$routes->post('app/bookings', 'BookingController::createBooking', ['filter' => 'webauth:bookings.manage']);
$routes->post('app/bookings/update', 'BookingController::updateBooking', ['filter' => 'webauth:bookings.manage']);
$routes->post('app/bookings/delete', 'BookingController::deleteBooking', ['filter' => 'webauth:bookings.manage']);
$routes->get('app/payments', 'PaymentController::index', ['filter' => 'webauth:payments.view']);
$routes->post('app/payments', 'PaymentController::createPayment', ['filter' => 'webauth:payments.manage']);
$routes->post('app/payments/update', 'PaymentController::updatePayment', ['filter' => 'webauth:payments.manage']);
$routes->post('app/payments/delete', 'PaymentController::deletePayment', ['filter' => 'webauth:payments.manage']);
$routes->get('app/branches', 'BranchController::index', ['filter' => 'webauth:branches.view']);
$routes->post('app/branches', 'BranchController::createBranch', ['filter' => 'webauth:branches.manage']);
$routes->post('app/branches/update', 'BranchController::updateBranch', ['filter' => 'webauth:branches.manage']);
$routes->post('app/branches/delete', 'BranchController::deleteBranch', ['filter' => 'webauth:branches.manage']);
$routes->get('app/agents', 'AgentController::index', ['filter' => 'webauth:agents.view']);
$routes->post('app/agents', 'AgentController::createAgent', ['filter' => 'webauth:agents.manage']);
$routes->post('app/agents/update', 'AgentController::updateAgent', ['filter' => 'webauth:agents.manage']);
$routes->post('app/agents/delete', 'AgentController::deleteAgent', ['filter' => 'webauth:agents.manage']);
$routes->get('app/users', 'UserController::index', ['filter' => 'webauth:users.view']);
$routes->get('app/users/add', 'UserController::add', ['filter' => 'webauth:users.manage']);
$routes->get('app/users/(:num)/edit', 'UserController::edit/$1', ['filter' => 'webauth:users.manage']);
$routes->post('app/users', 'UserController::createUser', ['filter' => 'webauth:users.manage']);
$routes->post('app/users/update', 'UserController::updateUser', ['filter' => 'webauth:users.manage']);
$routes->post('app/users/delete', 'UserController::deleteUser', ['filter' => 'webauth:users.manage']);
$routes->get('app/packages', 'PackageController::index', ['filter' => 'webauth:packages.view']);
$routes->post('app/packages', 'PackageController::createPackage', ['filter' => 'webauth:packages.manage']);
$routes->get('app/packages/add', 'PackageController::add', ['filter' => 'webauth:packages.manage']);
$routes->get('app/packages/(:num)/edit', 'PackageController::edit/$1', ['filter' => 'webauth:packages.manage']);
$routes->post('app/packages/update', 'PackageController::updatePackage', ['filter' => 'webauth:packages.manage']);
$routes->post('app/packages/delete', 'PackageController::deletePackage', ['filter' => 'webauth:packages.manage']);
$routes->post('app/packages/costs/create', 'PackageController::createPackageCost', ['filter' => 'webauth:packages.manage']);
$routes->post('app/packages/costs/delete', 'PackageController::deletePackageCost', ['filter' => 'webauth:packages.manage']);
$routes->post('app/packages/hotels/create', 'PackageController::createPackageHotel', ['filter' => 'webauth:packages.manage']);
$routes->post('app/packages/hotels/delete', 'PackageController::deletePackageHotel', ['filter' => 'webauth:packages.manage']);
$routes->post('app/packages/flights/create', 'PackageController::createPackageFlight', ['filter' => 'webauth:packages.manage']);
$routes->post('app/packages/flights/delete', 'PackageController::deletePackageFlight', ['filter' => 'webauth:packages.manage']);
$routes->post('app/packages/transports/create', 'PackageController::createPackageTransport', ['filter' => 'webauth:packages.manage']);
$routes->post('app/packages/transports/delete', 'PackageController::deletePackageTransport', ['filter' => 'webauth:packages.manage']);
$routes->post('app/packages/cost-sheet/save', 'PackageController::saveCostSheet', ['filter' => 'webauth:packages.manage']);
$routes->post('app/packages/cost-sheet/publish', 'PackageController::publishCostSheet', ['filter' => 'webauth:packages.manage']);
$routes->get('app/visas', 'VisaController::index', ['filter' => 'webauth:visas.view']);
$routes->get('app/visas/add', 'VisaController::add', ['filter' => 'webauth:visas.manage']);
$routes->get('app/visas/(:num)/edit', 'VisaController::edit/$1', ['filter' => 'webauth:visas.manage']);
$routes->post('app/visas', 'VisaController::createVisa', ['filter' => 'webauth:visas.manage']);
$routes->post('app/visas/update', 'VisaController::updateVisa', ['filter' => 'webauth:visas.manage']);
$routes->post('app/visas/status', 'VisaController::updateVisaStatus', ['filter' => 'webauth:visas.manage']);
$routes->post('app/visas/bulk-status', 'VisaController::bulkUpdateVisaStatus', ['filter' => 'webauth:visas.manage']);
$routes->post('app/visas/delete', 'VisaController::deleteVisa', ['filter' => 'webauth:visas.manage']);
$routes->get('app/flights', 'FlightController::index', ['filter' => 'webauth:flights.view']);
$routes->get('app/flights/add', 'FlightController::add', ['filter' => 'webauth:flights.manage']);
$routes->get('app/flights/departure-batches', 'FlightController::departureBatches', ['filter' => 'webauth:flights.view']);
$routes->get('app/flights/(:num)/edit', 'FlightController::edit/$1', ['filter' => 'webauth:flights.manage']);
$routes->post('app/flights', 'FlightController::createFlight', ['filter' => 'webauth:flights.manage']);
$routes->post('app/flights/update', 'FlightController::updateFlight', ['filter' => 'webauth:flights.manage']);
$routes->post('app/flights/delete', 'FlightController::deleteFlight', ['filter' => 'webauth:flights.manage']);
$routes->post('app/flights/packages', 'FlightController::assignPackageFlight', ['filter' => 'webauth:flights.manage']);
$routes->post('app/flights/packages/delete', 'FlightController::deletePackageFlight', ['filter' => 'webauth:flights.manage']);
$routes->get('app/transports', 'TransportController::index', ['filter' => 'webauth:transports.view']);
$routes->get('app/transports/add', 'TransportController::add', ['filter' => 'webauth:transports.manage']);
$routes->get('app/transports/(:num)/edit', 'TransportController::edit/$1', ['filter' => 'webauth:transports.manage']);
$routes->post('app/transports', 'TransportController::createTransport', ['filter' => 'webauth:transports.manage']);
$routes->post('app/transports/update', 'TransportController::updateTransport', ['filter' => 'webauth:transports.manage']);
$routes->post('app/transports/delete', 'TransportController::deleteTransport', ['filter' => 'webauth:transports.manage']);
$routes->post('app/transports/legs/create', 'TransportController::createTransportLeg', ['filter' => 'webauth:transports.manage']);
$routes->post('app/transports/legs/delete', 'TransportController::deleteTransportLeg', ['filter' => 'webauth:transports.manage']);
$routes->post('app/transports/legs/move', 'TransportController::moveTransportLeg', ['filter' => 'webauth:transports.manage']);
$routes->get('app/suppliers', 'SupplierController::index', ['filter' => 'webauth:payments.view']);
$routes->get('app/suppliers/add', 'SupplierController::add', ['filter' => 'webauth:payments.manage']);
$routes->get('app/suppliers/(:num)/edit', 'SupplierController::edit/$1', ['filter' => 'webauth:payments.manage']);
$routes->get('app/suppliers/(:num)/ledger', 'SupplierController::ledger/$1', ['filter' => 'webauth:payments.view']);
$routes->post('app/suppliers', 'SupplierController::createSupplier', ['filter' => 'webauth:payments.manage']);
$routes->post('app/suppliers/update', 'SupplierController::updateSupplier', ['filter' => 'webauth:payments.manage']);
$routes->post('app/suppliers/delete', 'SupplierController::deleteSupplier', ['filter' => 'webauth:payments.manage']);
$routes->post('app/suppliers/ledger', 'SupplierController::createLedgerEntry', ['filter' => 'webauth:payments.manage']);
$routes->get('app/hotels', 'HotelController::index', ['filter' => 'webauth:hotels.view']);
$routes->get('app/hotels/add', 'HotelController::add', ['filter' => 'webauth:hotels.manage']);
$routes->get('app/hotels/rooming-list', 'HotelController::roomingList', ['filter' => 'webauth:hotels.view']);
$routes->get('app/hotels/(:num)/edit', 'HotelController::edit/$1', ['filter' => 'webauth:hotels.manage']);
$routes->post('app/hotels', 'HotelController::createHotel', ['filter' => 'webauth:hotels.manage']);
$routes->post('app/hotels/update', 'HotelController::updateHotel', ['filter' => 'webauth:hotels.manage']);
$routes->post('app/hotels/delete', 'HotelController::deleteHotel', ['filter' => 'webauth:hotels.manage']);
$routes->post('app/hotels/rooms', 'HotelController::createRoom', ['filter' => 'webauth:hotels.manage']);
$routes->post('app/hotels/rooms/update', 'HotelController::updateRoom', ['filter' => 'webauth:hotels.manage']);
$routes->post('app/hotels/rooms/delete', 'HotelController::deleteRoom', ['filter' => 'webauth:hotels.manage']);
$routes->get('app/reports', 'ReportController::index', ['filter' => 'webauth:reports.view']);
$routes->get('app/audit', 'AuditLogController::index', ['filter' => 'webauth:audit.view']);
$routes->get('app/rbac', 'RbacController::index', ['filter' => 'webauth:rbac.manage']);
$routes->get('app/rbac/roles', 'RbacController::roles', ['filter' => 'webauth:rbac.manage']);
$routes->get('app/rbac/permissions', 'RbacController::permissions', ['filter' => 'webauth:rbac.manage']);
$routes->get('app/rbac/assign', 'RbacController::assign', ['filter' => 'webauth:rbac.manage']);
$routes->post('app/rbac/roles', 'RbacController::createRole', ['filter' => 'webauth:rbac.manage']);
$routes->post('app/rbac/permissions', 'RbacController::createPermission', ['filter' => 'webauth:rbac.manage']);
$routes->post('app/rbac/role-permissions', 'RbacController::syncRolePermissions', ['filter' => 'webauth:rbac.manage']);
$routes->post('app/rbac/user-roles', 'RbacController::assignUserRole', ['filter' => 'webauth:rbac.manage']);
