<?php

use CodeIgniter\Router\RouteCollection;

/**
 * @var RouteCollection $routes
 */
$routes->get('/', 'AuthController::loginForm');
$routes->get('packages/public', 'PackageController::publicIndex');
$routes->get('packages/register/(:num)', 'PackageController::register/$1');

$routes->get('login', 'AuthController::loginForm');
$routes->post('login', 'AuthController::loginSubmit');
$routes->get('unauthorized', 'AuthController::unauthorized', ['filter' => 'webauth']);
$routes->get('forgot-password', 'AuthController::forgotPasswordForm');
$routes->post('forgot-password', 'AuthController::forgotPasswordSubmit');
$routes->get('reset-password', 'AuthController::resetPasswordForm');
$routes->post('reset-password', 'AuthController::resetPasswordSubmit');
$routes->post('logout', 'AuthController::logout', ['filter' => 'webauth']);
$routes->get('dashboard', 'DashboardController::index', ['filter' => 'webauth:dashboard.view']);
$routes->get('seasons', 'SeasonController::index', ['filter' => 'webauth:rbac.manage']);
$routes->post('seasons', 'SeasonController::createSeason', ['filter' => 'webauth:rbac.manage']);
$routes->post('seasons/activate', 'SeasonController::activateSeason', ['filter' => 'webauth:rbac.manage']);
$routes->get('pilgrims', 'PilgrimController::index', ['filter' => 'webauth:pilgrims.view']);
$routes->post('pilgrims', 'PilgrimController::createPilgrim', ['filter' => 'webauth:pilgrims.manage']);
$routes->get('pilgrims/import', 'PilgrimController::importPage', ['filter' => 'webauth:pilgrims.manage']);
$routes->post('pilgrims/import', 'PilgrimController::importMofaCsv', ['filter' => 'webauth:pilgrims.manage']);
$routes->post('pilgrims/update', 'PilgrimController::updatePilgrim', ['filter' => 'webauth:pilgrims.manage']);
$routes->post('pilgrims/delete', 'PilgrimController::deletePilgrim', ['filter' => 'webauth:pilgrims.manage']);
$routes->get('pilgrims/add', 'PilgrimController::add', ['filter' => 'webauth:pilgrims.manage']);
$routes->get('pilgrims/(:num)/edit', 'PilgrimController::edit/$1', ['filter' => 'webauth:pilgrims.manage']);
$routes->get('bookings', 'BookingController::index', ['filter' => 'webauth:bookings.view']);
$routes->get('bookings/add', 'BookingController::add', ['filter' => 'webauth:bookings.manage']);
$routes->get('bookings/(:num)/edit', 'BookingController::edit/$1', ['filter' => 'webauth:bookings.manage']);
$routes->get('bookings/(:num)/voucher', 'BookingController::voucher/$1', ['filter' => 'webauth:bookings.view']);
$routes->post('bookings', 'BookingController::createBooking', ['filter' => 'webauth:bookings.manage']);
$routes->post('bookings/update', 'BookingController::updateBooking', ['filter' => 'webauth:bookings.manage']);
$routes->post('bookings/delete', 'BookingController::deleteBooking', ['filter' => 'webauth:bookings.manage']);
$routes->get('payments', 'PaymentController::index', ['filter' => 'webauth:payments.view']);
$routes->get('payments/create', 'PaymentController::createForm', ['filter' => 'webauth:payments.manage']);
$routes->get('payments/(:num)/view', 'PaymentController::show/$1', ['filter' => 'webauth:payments.view']);
$routes->get('payments/(:num)/edit', 'PaymentController::editForm/$1', ['filter' => 'webauth:payments.manage']);
$routes->get('payments/(:num)/receipt', 'PaymentController::receipt/$1', ['filter' => 'webauth:payments.view']);
$routes->post('payments', 'PaymentController::createPayment', ['filter' => 'webauth:payments.manage']);
$routes->post('payments/update', 'PaymentController::updatePayment', ['filter' => 'webauth:payments.manage']);
$routes->post('payments/delete', 'PaymentController::deletePayment', ['filter' => 'webauth:payments.manage']);
$routes->get('branches', 'BranchController::index', ['filter' => 'webauth:branches.view']);
$routes->post('branches', 'BranchController::createBranch', ['filter' => 'webauth:branches.manage']);
$routes->post('branches/update', 'BranchController::updateBranch', ['filter' => 'webauth:branches.manage']);
$routes->post('branches/delete', 'BranchController::deleteBranch', ['filter' => 'webauth:branches.manage']);
$routes->get('agents', 'AgentController::index', ['filter' => 'webauth:agents.view']);
$routes->get('agents/add', 'AgentController::add', ['filter' => 'webauth:agents.manage']);
$routes->get('agents/(:num)/edit', 'AgentController::edit/$1', ['filter' => 'webauth:agents.manage']);
$routes->get('agents/(:num)/ledger', 'AgentController::ledger/$1', ['filter' => 'webauth:agents.view']);
$routes->post('agents', 'AgentController::createAgent', ['filter' => 'webauth:agents.manage']);
$routes->post('agents/add', 'AgentController::createAgent', ['filter' => 'webauth:agents.manage']);
$routes->post('agents/update', 'AgentController::updateAgent', ['filter' => 'webauth:agents.manage']);
$routes->post('agents/delete', 'AgentController::deleteAgent', ['filter' => 'webauth:agents.manage']);
$routes->post('agents/ledger', 'AgentController::createLedgerEntry', ['filter' => 'webauth:agents.manage']);
$routes->get('users', 'UserController::index', ['filter' => 'webauth:users.view']);
$routes->get('users/add', 'UserController::add', ['filter' => 'webauth:users.manage']);
$routes->get('users/(:num)/edit', 'UserController::edit/$1', ['filter' => 'webauth:users.manage']);
$routes->post('users', 'UserController::createUser', ['filter' => 'webauth:users.manage']);
$routes->post('users/update', 'UserController::updateUser', ['filter' => 'webauth:users.manage']);
$routes->post('users/delete', 'UserController::deleteUser', ['filter' => 'webauth:users.manage']);
$routes->get('packages', 'PackageController::index', ['filter' => 'webauth:packages.view']);
$routes->post('packages', 'PackageController::createPackage', ['filter' => 'webauth:packages.manage']);
$routes->get('packages/add', 'PackageController::add', ['filter' => 'webauth:packages.manage']);
$routes->get('packages/(:num)/edit', 'PackageController::edit/$1', ['filter' => 'webauth:packages.manage']);
$routes->post('packages/update', 'PackageController::updatePackage', ['filter' => 'webauth:packages.manage']);
$routes->post('packages/delete', 'PackageController::deletePackage', ['filter' => 'webauth:packages.manage']);
$routes->post('packages/costs/create', 'PackageController::createPackageCost', ['filter' => 'webauth:packages.manage']);
$routes->post('packages/costs/delete', 'PackageController::deletePackageCost', ['filter' => 'webauth:packages.manage']);
$routes->post('packages/hotels/create', 'PackageController::createPackageHotel', ['filter' => 'webauth:packages.manage']);
$routes->post('packages/hotels/delete', 'PackageController::deletePackageHotel', ['filter' => 'webauth:packages.manage']);
$routes->post('packages/flights/create', 'PackageController::createPackageFlight', ['filter' => 'webauth:packages.manage']);
$routes->post('packages/flights/delete', 'PackageController::deletePackageFlight', ['filter' => 'webauth:packages.manage']);
$routes->post('packages/transports/create', 'PackageController::createPackageTransport', ['filter' => 'webauth:packages.manage']);
$routes->post('packages/transports/delete', 'PackageController::deletePackageTransport', ['filter' => 'webauth:packages.manage']);
$routes->post('packages/cost-sheet/save', 'PackageController::saveCostSheet', ['filter' => 'webauth:packages.manage']);
$routes->post('packages/cost-sheet/publish', 'PackageController::publishCostSheet', ['filter' => 'webauth:packages.manage']);
$routes->get('visas', 'VisaController::index', ['filter' => 'webauth:visas.view']);
$routes->get('visas/add', 'VisaController::add', ['filter' => 'webauth:visas.manage']);
$routes->get('visas/(:num)/edit', 'VisaController::edit/$1', ['filter' => 'webauth:visas.manage']);
$routes->post('visas', 'VisaController::createVisa', ['filter' => 'webauth:visas.manage']);
$routes->post('visas/update', 'VisaController::updateVisa', ['filter' => 'webauth:visas.manage']);
$routes->post('visas/status', 'VisaController::updateVisaStatus', ['filter' => 'webauth:visas.manage']);
$routes->post('visas/bulk-status', 'VisaController::bulkUpdateVisaStatus', ['filter' => 'webauth:visas.manage']);
$routes->post('visas/delete', 'VisaController::deleteVisa', ['filter' => 'webauth:visas.manage']);
$routes->get('flights', 'FlightController::index', ['filter' => 'webauth:flights.view']);
$routes->get('flights/add', 'FlightController::add', ['filter' => 'webauth:flights.manage']);
$routes->get('flights/departure-batches', 'FlightController::departureBatches', ['filter' => 'webauth:flights.view']);
$routes->get('flights/(:num)/edit', 'FlightController::edit/$1', ['filter' => 'webauth:flights.manage']);
$routes->post('flights', 'FlightController::createFlight', ['filter' => 'webauth:flights.manage']);
$routes->post('flights/update', 'FlightController::updateFlight', ['filter' => 'webauth:flights.manage']);
$routes->post('flights/delete', 'FlightController::deleteFlight', ['filter' => 'webauth:flights.manage']);
$routes->post('flights/packages', 'FlightController::assignPackageFlight', ['filter' => 'webauth:flights.manage']);
$routes->post('flights/packages/delete', 'FlightController::deletePackageFlight', ['filter' => 'webauth:flights.manage']);
$routes->get('transports', 'TransportController::index', ['filter' => 'webauth:transports.view']);
$routes->get('transports/add', 'TransportController::add', ['filter' => 'webauth:transports.manage']);
$routes->get('transports/(:num)/edit', 'TransportController::edit/$1', ['filter' => 'webauth:transports.manage']);
$routes->post('transports', 'TransportController::createTransport', ['filter' => 'webauth:transports.manage']);
$routes->post('transports/update', 'TransportController::updateTransport', ['filter' => 'webauth:transports.manage']);
$routes->post('transports/delete', 'TransportController::deleteTransport', ['filter' => 'webauth:transports.manage']);
$routes->post('transports/legs/create', 'TransportController::createTransportLeg', ['filter' => 'webauth:transports.manage']);
$routes->post('transports/legs/delete', 'TransportController::deleteTransportLeg', ['filter' => 'webauth:transports.manage']);
$routes->post('transports/legs/move', 'TransportController::moveTransportLeg', ['filter' => 'webauth:transports.manage']);
$routes->get('suppliers', 'SupplierController::index', ['filter' => 'webauth:payments.view']);
$routes->get('suppliers/add', 'SupplierController::add', ['filter' => 'webauth:payments.manage']);
$routes->get('suppliers/(:num)/edit', 'SupplierController::edit/$1', ['filter' => 'webauth:payments.manage']);
$routes->get('suppliers/(:num)/ledger', 'SupplierController::ledger/$1', ['filter' => 'webauth:payments.view']);
$routes->post('suppliers', 'SupplierController::createSupplier', ['filter' => 'webauth:payments.manage']);
$routes->post('suppliers/update', 'SupplierController::updateSupplier', ['filter' => 'webauth:payments.manage']);
$routes->post('suppliers/delete', 'SupplierController::deleteSupplier', ['filter' => 'webauth:payments.manage']);
$routes->post('suppliers/ledger', 'SupplierController::createLedgerEntry', ['filter' => 'webauth:payments.manage']);
$routes->get('companies', 'CompanyController::index', ['filter' => 'webauth:companies.view']);
$routes->post('companies', 'CompanyController::createCompany', ['filter' => 'webauth:companies.manage']);
$routes->post('companies/update', 'CompanyController::updateCompany', ['filter' => 'webauth:companies.manage']);
$routes->post('companies/delete', 'CompanyController::deleteCompany', ['filter' => 'webauth:companies.manage']);
$routes->get('main-company', 'MainCompanyController::index', ['filter' => 'webauth:companies.view']);
$routes->post('main-company/update', 'MainCompanyController::update', ['filter' => 'webauth:companies.manage']);
$routes->get('hotels', 'HotelController::index', ['filter' => 'webauth:hotels.view']);
$routes->get('hotels/add', 'HotelController::add', ['filter' => 'webauth:hotels.manage']);
$routes->get('hotels/rooming-list', 'HotelController::roomingList', ['filter' => 'webauth:hotels.view']);
$routes->get('hotels/(:num)', 'HotelController::details/$1', ['filter' => 'webauth:hotels.view']);
$routes->get('hotels/(:num)/edit', 'HotelController::edit/$1', ['filter' => 'webauth:hotels.manage']);
$routes->post('hotels', 'HotelController::createHotel', ['filter' => 'webauth:hotels.manage']);
$routes->post('hotels/update', 'HotelController::updateHotel', ['filter' => 'webauth:hotels.manage']);
$routes->post('hotels/delete', 'HotelController::deleteHotel', ['filter' => 'webauth:hotels.manage']);
$routes->post('hotels/gallery/delete', 'HotelController::deleteHotelImage', ['filter' => 'webauth:hotels.manage']);
$routes->post('hotels/rooms', 'HotelController::createRoom', ['filter' => 'webauth:hotels.manage']);
$routes->post('hotels/rooms/update', 'HotelController::updateRoom', ['filter' => 'webauth:hotels.manage']);
$routes->post('hotels/rooms/delete', 'HotelController::deleteRoom', ['filter' => 'webauth:hotels.manage']);
$routes->get('reports', 'ReportController::index', ['filter' => 'webauth:reports.view']);
$routes->get('audit', 'AuditLogController::index', ['filter' => 'webauth:audit.view']);
$routes->get('rbac', 'RbacController::index', ['filter' => 'webauth:rbac.manage']);
$routes->get('rbac/roles', 'RbacController::roles', ['filter' => 'webauth:rbac.manage']);
$routes->get('rbac/permissions', 'RbacController::permissions', ['filter' => 'webauth:rbac.manage']);
$routes->get('rbac/assign', 'RbacController::assign', ['filter' => 'webauth:rbac.manage']);
$routes->post('rbac/roles', 'RbacController::createRole', ['filter' => 'webauth:rbac.manage']);
$routes->post('rbac/permissions', 'RbacController::createPermission', ['filter' => 'webauth:rbac.manage']);
$routes->post('rbac/role-permissions', 'RbacController::syncRolePermissions', ['filter' => 'webauth:rbac.manage']);
$routes->post('rbac/user-roles', 'RbacController::assignUserRole', ['filter' => 'webauth:rbac.manage']);

$routes->addRedirect('app', 'dashboard', 302);
$routes->addRedirect('app/(.*)', '$1', 302);
