-- Migration for extended packages table
CREATE TABLE packages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(40) NOT NULL,
    name VARCHAR(180) NOT NULL,
    package_type VARCHAR(20) NOT NULL,
    airline VARCHAR(100),
    airline_logo VARCHAR(255),
    departure_date DATE NOT NULL,
    arrival_date DATE NOT NULL,
    duration_days INT NOT NULL,
    days_distribution VARCHAR(50),
    makkah_hotel VARCHAR(100),
    makkah_hotel_link VARCHAR(255),
    madina_hotel VARCHAR(100),
    madina_hotel_link VARCHAR(255),
    sharing_types VARCHAR(50),
    selling_price DECIMAL(10,2) NOT NULL,
    purchase_price_total DECIMAL(10,2),
    purchase_price_visa DECIMAL(10,2),
    purchase_price_ticket DECIMAL(10,2),
    purchase_price_transport DECIMAL(10,2),
    purchase_price_makkah DECIMAL(10,2),
    purchase_price_madina DECIMAL(10,2),
    passport_attachment VARCHAR(255),
    total_seats INT NOT NULL,
    is_active TINYINT(1) DEFAULT 1,
    notes TEXT,
    created_at DATETIME,
    updated_at DATETIME
);
